### PR TITLE
Accept `brand` setting when creating events

### PR DESCRIPTION
**Pull request by compwright**
Add `brand` to the `.shootproof` config file, or specify on the command line with `--brand=<id>`.

### CODE REVIEW

**Comment by compwright** [comment]
Note that this needs https://github.com/ShootProof/php-sdk/pull/10 before it is built and released.

**Comment by rswarthout** [comment]
@compwright The php-sdk has been updated and tagged with 1.1.2.

**Comment by ramsey** [comment]
@compwright, please run CodeSniffer locally and fix the errors. That's what's causing the build to break:

```
./vendor/bin/phpcs src bin bin/shootproof-cli --standard=psr2 -sp
```

Is the `brandId` setting now required, or is it optional? If it's required, then this breaks BC, and we need to think about releasing this as version `2.0.0` rather than `1.2.0`. Folks using `~1.1` or `^1.1.0` in their `composer.json` files will automatically get bumped to `1.2.0`, and that could cause problems with a BC break.

**Comment by compwright** [comment]
@ramsey `brand` is not required. Were you seeing otherwise somewhere?

**Comment by ramsey** [comment]
@compwright Oops! I failed to see that `$brandId` defaults to `null`. All is good, then. :-)

**Comment by compwright** [comment]
FYI a second PR is coming adding a brandinfo command, so no need to go to the trouble of releasing just yet after this is merged.

**Comment by ramsey** [comment]
Sounds good. We'll do a `1.2.0` release and package a new Phar to put on the releases page for download, once that PR is merged in.

**Comment by compwright** [comment]
@ramsey @rswarthout Added the `brands` command, this is good to be merged and released. I'm sure Joe Paetzel would appreciate having this done before the holiday. Thanks for all your help on this!

**Comment by DeliveryGuy** [comment]
I'll second the desire to get this released before the Holiday. Thanks everyone!

**Comment by ramsey** [comment]
New release is [available here](https://github.com/ShootProof/shootproof-cli/releases/latest). Enjoy, and have a happy Thanksgiving!

**Pull request merged**
